/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const message: typeof import('ant-design-vue').message
  const notification: typeof import('ant-design-vue').notification
}
