/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADatePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['default']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BacktestResult: typeof import('./src/components/backtest/BacktestResult.vue')['default']
    BacktestTrades: typeof import('./src/components/backtest/BacktestTrades.vue')['default']
    ComponentStatus: typeof import('./src/components/system/ComponentStatus.vue')['default']
    ConnectorHealthCards: typeof import('./src/components/quality/ConnectorHealthCards.vue')['default']
    DrawdownChart: typeof import('./src/components/risk/DrawdownChart.vue')['default']
    EquityChart: typeof import('./src/components/dashboard/EquityChart.vue')['default']
    EquityCurve: typeof import('./src/components/backtest/EquityCurve.vue')['default']
    ExposureTable: typeof import('./src/components/risk/ExposureTable.vue')['default']
    HealthStatus: typeof import('./src/components/system/HealthStatus.vue')['default']
    KillSwitchBar: typeof import('./src/components/risk/KillSwitchBar.vue')['default']
    MetricsCards: typeof import('./src/components/backtest/MetricsCards.vue')['default']
    OpenOrdersTable: typeof import('./src/components/orders/OpenOrdersTable.vue')['default']
    OrderEventTimeline: typeof import('./src/components/orders/OrderEventTimeline.vue')['default']
    OrderForm: typeof import('./src/components/orders/OrderForm.vue')['default']
    OrderHistoryTable: typeof import('./src/components/orders/OrderHistoryTable.vue')['default']
    PositionsDonut: typeof import('./src/components/dashboard/PositionsDonut.vue')['default']
    PositionTable: typeof import('./src/components/dashboard/PositionTable.vue')['default']
    QualityAlertsFeed: typeof import('./src/components/quality/QualityAlertsFeed.vue')['default']
    RecentTrades: typeof import('./src/components/dashboard/RecentTrades.vue')['default']
    RiskConfigCards: typeof import('./src/components/risk/RiskConfigCards.vue')['default']
    RiskEventsTable: typeof import('./src/components/risk/RiskEventsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    SignalFeed: typeof import('./src/components/signals/SignalFeed.vue')['default']
    SignalSummary: typeof import('./src/components/signals/SignalSummary.vue')['default']
    StatCards: typeof import('./src/components/dashboard/StatCards.vue')['default']
    StrategyDetail: typeof import('./src/components/strategies/StrategyDetail.vue')['default']
    StrategyList: typeof import('./src/components/strategies/StrategyList.vue')['default']
    SystemStatusBar: typeof import('./src/components/dashboard/SystemStatusBar.vue')['default']
    WindowsTable: typeof import('./src/components/walkforward/WindowsTable.vue')['default']
  }
}
